import React, { useState } from "react";
import {
  ShieldCheck,
  Zap,
  Info,
  Award,
  CheckCircle2,
  Copy,
  Code,
  FileText,
  Check,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Radar,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  ResponsiveContainer,
  RadialBarChart,
  RadialBar,
  PolarRadiusAxis,
} from "recharts";

// 🧹 Helper: Cleans Gemini's Markdown (removes **, ##, etc.)
const cleanText = (text) => {
  if (!text) return "";
  return text.replace(/[*_#`]/g, "").trim();
};

export const ResumeResult = ({ result }) => {
  const [showLatex, setShowLatex] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!result) return null;

  // 📊 1. Prepare Data for Radar Chart (Skill Breakdown)
  // Defaults to 50 if data is missing to prevent crash
  const radarData = [
    {
      subject: "Structure",
      A: result.breakdown?.Structure || 65,
      fullMark: 100,
    },
    { subject: "Impact", A: result.breakdown?.Impact || 55, fullMark: 100 },
    { subject: "Keywords", A: result.breakdown?.Keywords || 75, fullMark: 100 },
    {
      subject: "Technical",
      A: result.breakdown?.Technical || 80,
      fullMark: 100,
    },
  ];

  // 📊 2. Prepare Data for Radial Bar (Main Score)
  const scoreData = [
    { name: "Score", value: result.score || 0, fill: "#8b5cf6" },
  ];

  // 📋 Copy LaTeX Function
  const handleCopyLatex = () => {
    const code = result.latex_code || "% No LaTeX code generated by AI";
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // ✨ Animation Variants
  const containerVars = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0, transition: { staggerChildren: 0.1 } },
  };

  const itemVars = {
    initial: { opacity: 0, x: -20 },
    animate: { opacity: 1, x: 0 },
  };

  return (
    <motion.div
      variants={containerVars}
      initial="initial"
      animate="animate"
      className="mt-12 space-y-8 max-w-6xl mx-auto pb-20 px-4"
    >
      {/* 🏆 TOP ROW: Score & Radar Chart */}
      <div className="grid md:grid-cols-5 gap-6">
        {/* LEFT: MAIN SCORE (Radial Gauge) */}
        <motion.div
          variants={itemVars}
          className="md:col-span-2 relative overflow-hidden rounded-[2.5rem] bg-white/60 border border-white/50 backdrop-blur-xl shadow-xl p-8 flex flex-col items-center justify-center text-center group hover:shadow-2xl transition-all duration-500"
        >
          <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-blue-500/5 group-hover:opacity-100 transition-opacity" />

          <h3 className="text-xs font-bold uppercase tracking-[0.2em] text-gray-400 mb-4">
            AI Quality Index
          </h3>

          <div className="relative size-64">
            <ResponsiveContainer width="100%" height="100%">
              <RadialBarChart
                innerRadius="70%"
                outerRadius="100%"
                barSize={20}
                data={scoreData}
                startAngle={90}
                endAngle={-270}
              >
                <PolarAngleAxis
                  type="number"
                  domain={[0, 100]}
                  angleAxisId={0}
                  tick={false}
                />
                <RadialBar
                  background
                  clockWise
                  dataKey="value"
                  cornerRadius={30}
                />
              </RadialBarChart>
            </ResponsiveContainer>

            {/* Score Overlay */}
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <motion.span
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                className="text-7xl font-heading font-black text-transparent bg-clip-text bg-gradient-to-br from-purple-600 to-blue-600"
              >
                {result.score}
              </motion.span>
              <span className="text-sm font-medium text-gray-400">/ 100</span>
            </div>
          </div>

          <div className="mt-4 px-5 py-2 bg-purple-50 rounded-full text-purple-700 text-xs font-bold border border-purple-100 flex items-center gap-2">
            <Award size={14} /> Top {100 - (result.score || 50)}% of candidates
          </div>
        </motion.div>

        {/* RIGHT: SKILL RADAR (Spider Chart) */}
        <motion.div
          variants={itemVars}
          className="md:col-span-3 relative overflow-hidden rounded-[2.5rem] bg-white/60 border border-white/50 backdrop-blur-xl shadow-xl p-6 flex flex-col"
        >
          <div className="absolute top-0 right-0 p-8 opacity-5">
            <FileText size={150} />
          </div>

          <div className="mb-2 pl-4 z-10">
            <h3 className="text-xl font-bold text-gray-800">
              Performance Breakdown
            </h3>
            <p className="text-sm text-gray-500">
              Analysis of key recruiting metrics
            </p>
          </div>

          <div className="flex-1 min-h-[300px] z-10">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                <PolarGrid stroke="#e5e7eb" />
                <PolarAngleAxis
                  dataKey="subject"
                  tick={{ fill: "#6b7280", fontSize: 12, fontWeight: "bold" }}
                />
                <PolarRadiusAxis
                  angle={30}
                  domain={[0, 100]}
                  tick={false}
                  axisLine={false}
                />
                <Radar
                  name="Resume"
                  dataKey="A"
                  stroke="#8b5cf6"
                  strokeWidth={3}
                  fill="#8b5cf6"
                  fillOpacity={0.4}
                />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
      </div>

      {/* 📝 BOTTOM ROW: Strengths & Improvements */}
      <div className="grid md:grid-cols-2 gap-8">
        {/* ✅ STRENGTHS */}
        <motion.div
          variants={itemVars}
          className="relative p-8 rounded-[2rem] bg-emerald-50/40 border border-emerald-100 backdrop-blur-sm"
        >
          <h3 className="flex items-center gap-2 font-bold text-emerald-800 mb-6 text-lg">
            <ShieldCheck className="text-emerald-500" /> What You Did Well
          </h3>
          <ul className="space-y-4">
            {result.strengths?.map((s, i) => (
              <motion.li
                key={i}
                whileHover={{ x: 5 }}
                className="flex items-start gap-3"
              >
                <CheckCircle2
                  size={18}
                  className="mt-1 text-emerald-500 shrink-0"
                />
                <p className="text-emerald-900/80 text-sm font-medium leading-relaxed">
                  {cleanText(s)}
                </p>
              </motion.li>
            ))}
          </ul>
        </motion.div>

        {/* 🚀 IMPROVEMENTS & LATEX TOGGLE */}
        <motion.div
          variants={itemVars}
          className="relative p-8 rounded-[2rem] bg-amber-50/40 border border-amber-100 backdrop-blur-sm flex flex-col"
        >
          <div className="flex items-center justify-between mb-6">
            <h3 className="flex items-center gap-2 font-bold text-amber-800 text-lg">
              <Zap className="text-amber-500" /> Actionable Improvements
            </h3>

            {/* Toggle Button */}
            <button
              onClick={() => setShowLatex(!showLatex)}
              className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-amber-800 bg-amber-200/50 hover:bg-amber-200 rounded-lg transition-colors border border-amber-200"
            >
              <Code size={14} />
              {showLatex ? "Show List" : "Get LaTeX"}
            </button>
          </div>

          <AnimatePresence mode="wait">
            {showLatex ? (
              // 🖥️ LATEX CODE VIEW
              <motion.div
                key="latex"
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="bg-slate-900 rounded-xl p-4 overflow-hidden relative group"
              >
                <div className="flex justify-between items-center mb-2 border-b border-slate-700 pb-2">
                  <span className="text-xs text-slate-400 font-mono">
                    improvements.tex
                  </span>
                  <button
                    onClick={handleCopyLatex}
                    className="text-slate-400 hover:text-white transition-colors"
                  >
                    {copied ? (
                      <Check size={14} className="text-green-400" />
                    ) : (
                      <Copy size={14} />
                    )}
                  </button>
                </div>
                <pre className="text-xs text-green-400 font-mono overflow-x-auto whitespace-pre-wrap max-h-[300px] custom-scrollbar">
                  {result.latex_code || "% No LaTeX code available."}
                </pre>
              </motion.div>
            ) : (
              // 📝 LIST VIEW
              <motion.ul
                key="list"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="space-y-4"
              >
                {result.improvements?.map((imp, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <div className="mt-2 size-1.5 rounded-full bg-amber-500 shrink-0" />
                    <p className="text-amber-900/80 text-sm font-medium leading-relaxed">
                      {cleanText(imp)}
                    </p>
                  </li>
                ))}
              </motion.ul>
            )}
          </AnimatePresence>
        </motion.div>
      </div>

      {/* 💡 ATS TIPS FOOTER */}
      <motion.div
        variants={itemVars}
        className="p-8 rounded-[2rem] bg-gradient-to-r from-slate-900 to-slate-800 text-white shadow-2xl"
      >
        <div className="flex items-center gap-3 mb-6">
          <Info className="text-blue-400" />
          <h3 className="font-bold text-lg">Recruiter's Secret Notes</h3>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {result.ats_tips?.map((tip, i) => (
            <div
              key={i}
              className="bg-white/10 p-4 rounded-xl border border-white/5 text-sm text-slate-200"
            >
              {cleanText(tip)}
            </div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  );
};
